version: '3.8'

services:
  llm-pack-service:
    build: .
    ports:
      - "8808:8808"
    working_dir: /app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
