[project]
name = "llm-pack-service"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.95.0",  # StreamingResponse was introduced in 0.95.0
    "httpx>=0.28.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
